--- Inserciones

insert into TbCent_Salud  values (6266,'03 DE FEBRERO')
insert into TbCent_Salud  values (6244,'200 MILLAS')
insert into TbCent_Salud  values (6230,'ACAPULCO')
insert into TbCent_Salud  values (6241,'AEROPUERTO')
insert into TbCent_Salud  values (6221,'ALBERTO BARTON')
insert into TbCent_Salud  values (6250,'ALTA MAR')
insert into TbCent_Salud  values (6257,'ANGAMOS')
insert into TbCent_Salud  values (6264,'BAHIA BLANCA')
insert into TbCent_Salud  values (6249,'BELLAVISTA')
insert into TbCent_Salud  values (6245,'BOCANEGRA')
insert into TbCent_Salud  values (7314,'C.MAT.INF.PERU COREA PACHACUTEC')
insert into TbCent_Salud  values (6222,'CALLAO')
insert into TbCent_Salud  values (6252,'CARMEN DE LA LEGUA')
insert into TbCent_Salud  values (6237,'CDJ')
insert into TbCent_Salud  values (6267,'CIUDAD PACHACUTEC')
insert into TbCent_Salud  values (6268,'DEFENSORES DE LA PATRIA')
insert into TbCent_Salud  values (6246,'EL ALAMO')
insert into TbCent_Salud  values (6236,'EL AYLLU')
insert into TbCent_Salud  values (6243,'FAUCETT')
insert into TbCent_Salud  values (6228,'GAMBETTA ALTA')
insert into TbCent_Salud  values (6232,'GAMBETTA BAJA')
insert into TbCent_Salud  values (6262,'HIJOS DE GRAU')
insert into TbCent_Salud  values (7316,'HOSPITAL DANIEL A CARRION')
insert into TbCent_Salud  values (7315,'HOSPITAL SAN JOSE')
insert into TbCent_Salud  values (7126,'HOSPITAL VENTANILLA')
insert into TbCent_Salud  values (6224,'JOSE BOTERIN')
insert into TbCent_Salud  values (6229,'JOSE OLAYA')
insert into TbCent_Salud  values (6233,'JUAN PABLO II')
insert into TbCent_Salud  values (6251,'LA PERLA')
insert into TbCent_Salud  values (6227,'LA PUNTA')
insert into TbCent_Salud  values (6261,'LUIS FELIPE DE LAS CASAS')
insert into TbCent_Salud  values (6220,'MANUAL BONILLA')
insert into TbCent_Salud  values (6238,'MARQUEZ')
insert into TbCent_Salud  values (6260,'MI PERU')
insert into TbCent_Salud  values (6235,'MIGUEL GRAU')
insert into TbCent_Salud  values (6768,'OQUENDO')
insert into TbCent_Salud  values (6242,'PLAYA RIMAC')
insert into TbCent_Salud  values (6248,'POLIGONO IV')
insert into TbCent_Salud  values (6240,'PREVI')
insert into TbCent_Salud  values (6226,'PUERTO NUEVO')
insert into TbCent_Salud  values (6231,'RAMON CASTILLA')
insert into TbCent_Salud  values (6225,'SAN JUAN BOSCO')
insert into TbCent_Salud  values (7321,'SANIDADES AEREA')
insert into TbCent_Salud  values (7322,'SANIDADES MARITIMAS')
insert into TbCent_Salud  values (6223,'SANTA FE')
insert into TbCent_Salud  values (6234,'SANTA ROSA')
insert into TbCent_Salud  values (6263,'SANTA ROSA PACHACUTEC')
insert into TbCent_Salud  values (6239,'SESQUICENTENARIO')
insert into TbCent_Salud  values (6255,'VENTANILLA ALTA')
insert into TbCent_Salud  values (6258,'VENTANILLA BAJA')
insert into TbCent_Salud  values (6259,'VENTANILLA ESTE')
insert into TbCent_Salud  values (6256,'VILLA LOS REYES')
insert into TbCent_Salud  values (6253,'VILLA SR. MILAGROS')
insert into TbCent_Salud  values (0,'--SELECCIONE--')
